
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 06 11:02:39 PYT 2015
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISPLAY = 2;
  public static final int DIVIDE = 31;
  public static final int MTHAN = 33;
  public static final int DOUBLE = 19;
  public static final int LPAREN = 37;
  public static final int PRIVATE = 5;
  public static final int INT = 18;
  public static final int FOR = 15;
  public static final int MINUS = 28;
  public static final int RPAREN = 38;
  public static final int STATIC = 10;
  public static final int OKEY = 43;
  public static final int OBRACKET = 41;
  public static final int SEMICOLON = 40;
  public static final int NOT = 36;
  public static final int AND = 34;
  public static final int LTHAN = 32;
  public static final int CBRACKET = 42;
  public static final int OR = 35;
  public static final int COMMA = 45;
  public static final int CKEY = 44;
  public static final int CLASS = 6;
  public static final int PLUS = 27;
  public static final int MAIN = 12;
  public static final int IF = 13;
  public static final int THIS = 17;
  public static final int NUMBERS = 47;
  public static final int DOT = 39;
  public static final int EOF = 0;
  public static final int BOOLEAN = 20;
  public static final int RETURN = 11;
  public static final int TRUE = 24;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int BECOMES = 29;
  public static final int NULL = 8;
  public static final int VOID = 9;
  public static final int IMPORT = 3;
  public static final int TIMES = 30;
  public static final int ELSE = 14;
  public static final int WHILE = 16;
  public static final int PUBLIC = 4;
  public static final int EXTENDS = 26;
  public static final int SYSTEMOUTPRINTLN = 23;
  public static final int STRING = 21;
  public static final int FALSE = 25;
  public static final int LENGTH = 22;
  public static final int IDENTIFIER = 46;
}

