
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 12 14:01:24 PYST 2014
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT = 5;
  public static final int LBRACE = 3;
  public static final int INTEGER = 12;
  public static final int DISPLAY = 2;
  public static final int BOOLEAN = 6;
  public static final int EOF = 0;
  public static final int PLUS = 7;
  public static final int BECOMES = 8;
  public static final int error = 1;
  public static final int SEMICOLON = 11;
  public static final int RPAREN = 10;
  public static final int IDENTIFIER = 13;
  public static final int LPAREN = 9;
  public static final int RBRACE = 4;
}

